"""Extract MSL components for MLX metal_kernel dispatch.

Parses the full MSL source generated by our codegen (MSLCodeGen.emit())
and extracts the kernel body, header, and argument mappings needed by
mx.fast.metal_kernel().

MLX's metal_kernel auto-injects thread variables when they appear in the
SOURCE string (not header). We prepend local variable declarations to the
body to trigger injection and compute pid/lid from the injected variables.
"""

import re
from dataclasses import dataclass
from typing import List, Optional, Set


@dataclass
class MSLExtraction:
    """Components extracted from full MSL for metal_kernel dispatch."""

    kernel_name: str
    body: str  # Kernel body (between { })
    header: str  # Device functions, non-standard includes
    input_names: List[str]  # Read-only pointer arg names
    output_names: List[str]  # Written-to pointer arg names
    scalar_names: List[str]  # Non-pointer buffer arg names (xnumel, etc.)
    scalar_types: List[str]  # MSL types for scalar args (int, float, etc.)
    output_ptr_indices: set = None  # Indices within ptr_args that are outputs
    uses_simd: bool = False
    uses_2d: bool = False
    uses_tpg: bool = False
    tpg_axes: Set[int] = None  # Which grid axes tpg is needed for (0, 1, 2)
    arg_positions: Optional[List[int]] = None  # Pointer-then-scalar order -> source runtime positions


def _reads_output(body: str, name: str) -> bool:
    """Conservatively prove write-only uses of an output and its emitted aliases.

    Exempt only the *base identifier* of an address/store, not the enclosing
    expression: both an alias offset and a store index may READ that same output.
    Unknown pointer spellings refuse; this is not a general-purpose MSL parser.
    """
    text = re.sub(r"//[^\n]*|/\*[\s\S]*?\*/", "", body)
    pending, seen = [name], set()
    safe_uses = set()
    declarations = list(re.finditer(r"(?:volatile\s+)?device\s+\w+\s*\*\s+(\w+)\s*=\s*([^;]+);", text))
    while pending:
        n = pending.pop()
        if n in seen:
            continue
        seen.add(n)
        for decl in declarations:
            # Only the emitter's direct base / optional device-pointer-cast
            # form establishes an alias. In particular `(device int*)o[0]`
            # is a load converted to a pointer, NOT a pointer alias.
            head = re.match(
                r"\s*(?:\(\s*(?:volatile\s+)?device\s+\w+\s*\*\s*\)\s*)?"
                r"(?:\(\s*)*(" + re.escape(n) + r")\b(?=\s*(?:[+\-)]|$))",
                decl.group(2),
            )
            if head is not None:
                safe_uses.add(decl.start(2) + head.start(1))
                safe_uses.add(decl.start(1))  # the alias's definition, not a read
                pending.append(decl.group(1))

        for use in re.finditer(r"\b" + re.escape(n) + r"\b", text):
            if use.start() in safe_uses:
                continue
            # Balance nested subscripts, but exempt ONLY the left-hand base.
            # All names inside the index remain visible to this same walk.
            i = use.end()
            while i < len(text) and text[i].isspace():
                i += 1
            if i < len(text) and text[i] == "[":
                depth = 1
                i += 1
                while i < len(text) and depth:
                    depth += (text[i] == "[") - (text[i] == "]")
                    i += 1
                while i < len(text) and text[i].isspace():
                    i += 1
                if depth == 0 and text[i : i + 1] == "=" and text[i : i + 2] != "==":
                    safe_uses.add(use.start())
                    continue
            return True  # load, atomic, escaping address, or unknown syntax
    return False


def extract_msl_for_mlx(
    msl_source: str,
    output_arg_indices: Optional[List[int]] = None,
    expected_args: Optional[int] = None,
    expected_signature: Optional[List[tuple]] = None,
) -> MSLExtraction:
    """Parse full MSL into components for mx.fast.metal_kernel().

    Args:
        msl_source: Complete MSL source from emit_msl().
        output_arg_indices: Indices of pointer args that are stored-to.
            If None, all pointer args are treated as outputs (conservative).

    Returns:
        MSLExtraction with body, header, and arg mappings.
    """
    # Split into pre-kernel (includes, device functions) and kernel
    kernel_match = re.search(r"^kernel\s+void\s+(\w+)\s*\(", msl_source, re.MULTILINE)
    if not kernel_match:
        raise ValueError("No kernel function found in MSL source")
    _n_kernels = len(re.findall(r"^kernel\s+void\s+", msl_source, re.MULTILINE))
    if _n_kernels != 1:
        # packet 176: the body is cut from the first `kernel void` to the LAST brace; a second
        # kernel (a two-kernel split, a fast + fallback pair) would be swallowed into the body.
        from triton_msl.errors import MetalNonRecoverableError

        raise MetalNonRecoverableError(
            f"MLX route: the emitted MSL holds {_n_kernels} kernels; mx.fast.metal_kernel dispatches one. Refusing."
        )

    kernel_name = kernel_match.group(1)
    pre_kernel = msl_source[: kernel_match.start()].strip()

    # Find kernel signature end (closing paren before opening brace)
    sig_start = kernel_match.start()
    brace_match = re.search(r"\)\s*\{", msl_source[sig_start:])
    if not brace_match:
        raise ValueError("Could not find kernel body opening brace")

    body_start = sig_start + brace_match.end()

    # Find matching closing brace (last `}` in source)
    body_end = msl_source.rstrip().rfind("}")
    if body_end < body_start:
        raise ValueError("Could not find kernel body closing brace")

    raw_body = msl_source[body_start:body_end]

    # Parse signature to extract args
    sig_text = msl_source[sig_start : sig_start + brace_match.start() + 1]
    ptr_args, scalar_args, thread_vars, arg_positions = _parse_signature(sig_text)
    if expected_args is not None and len(ptr_args) + len(scalar_args) != expected_args:
        # packet 176: the launcher binds the Triton arguments positionally; a signature the
        # parser reads differently from the Triton signature (a packed scalar buffer, a
        # `const device` pointer the pattern skips, a template-ordered ABI) is a silent mis-bind.
        from triton_msl.errors import MetalNonRecoverableError

        raise MetalNonRecoverableError(
            f"MLX route: the emitted kernel signature has {len(ptr_args)} pointer + {len(scalar_args)} "
            f"scalar arguments but the Triton signature has {expected_args} runtime arguments; refusing "
            f"rather than binding positionally."
        )

    # Counts alone do not establish an ABI: the same count can hide reordered
    # roles, a scalar exposed as a pointer, or an incorrect storage width.
    # Buffer positions are the generic emitter's source runtime positions.
    from triton_msl.errors import MetalNonRecoverableError

    n_buffers = len(re.findall(r"\[\[\s*buffer\s*\(", sig_text))
    if n_buffers != len(arg_positions) or sorted(arg_positions) != list(range(n_buffers)):
        raise MetalNonRecoverableError(
            "MLX route: kernel buffer bindings are not a complete unique runtime-argument map."
        )
    if expected_signature is not None:
        from triton_msl.codegen.msl_emitter import _sanitize_msl_name, triton_type_to_msl

        if len(expected_signature) != n_buffers:
            raise MetalNonRecoverableError("MLX route: source signature and kernel buffer counts differ.")
        for ordinal, ((name, dtype), source_pos) in enumerate(zip(ptr_args + scalar_args, arg_positions)):
            source_name, source_type = expected_signature[source_pos]
            is_ptr = ordinal < len(ptr_args)
            source_ptr = source_type.startswith("*")
            source_dtype = triton_type_to_msl(source_type[1:] if source_ptr else source_type)
            if name != _sanitize_msl_name(source_name) or is_ptr != source_ptr or dtype != source_dtype:
                raise MetalNonRecoverableError(
                    f"MLX route: buffer {source_pos} does not preserve source argument '{source_name}' "
                    f"({source_type}); emitted '{name}' is {'pointer' if is_ptr else 'scalar'} {dtype}. Refusing."
                )
    if output_arg_indices is not None:
        ptr_positions = set(arg_positions[: len(ptr_args)])
        if any(type(i) is not int or i not in ptr_positions for i in output_arg_indices):
            raise MetalNonRecoverableError("MLX route: an output argument index does not identify a source pointer.")

    # Classify pointer args as input vs output
    output_indices = set(output_arg_indices) if output_arg_indices else None
    input_names = []
    output_names = []
    output_ptr_idx_set = set()
    for i, (name, _dtype) in enumerate(ptr_args):
        if output_indices is None or arg_positions[i] in output_indices:
            output_names.append(name)
            output_ptr_idx_set.add(i)
        else:
            input_names.append(name)
    # packet 176: an output the kernel also reads (an accumulating / in-place store, an atomic on
    # it, a cast of its address) cannot be expressed through fresh MLX outputs — refuse. With
    # output_arg_indices=None EVERY pointer is an output, so a kernel that reads any pointer
    # refuses too (the old "conservative" mode handed the kernel uninitialised inputs).
    for name in output_names:
        if _reads_output(raw_body, name):
            from triton_msl.errors import MetalNonRecoverableError

            raise MetalNonRecoverableError(
                f"MLX route: the kernel reads (or atomically updates) its output pointer '{name}'; "
                f"mx.fast.metal_kernel outputs are fresh, uninitialised arrays, so the read would see "
                f"garbage. Use the torch.mps path for accumulating / in-place / atomic outputs."
            )

    scalar_names = [name for name, _ty in scalar_args]
    scalar_types = [ty for _name, ty in scalar_args]

    # Detect features
    uses_simd = "sgitg" in thread_vars or "tiisg" in thread_vars
    uses_2d = "pid3" in sig_text or "pid_y" in raw_body
    uses_tpg = "tpg" in thread_vars or "tpg3" in thread_vars

    # Detect which tpg axes are needed (from body references and signature)
    tpg_axes: Set[int] = set()
    if uses_tpg:
        tpg_axes.add(0)  # tpg (axis 0) always present when uses_tpg
    # Check for multi-axis tpg in the body (emitted as tpg_y, tpg_z)
    if re.search(r"\btpg_y\b", raw_body):
        tpg_axes.add(1)
        uses_tpg = True
    if re.search(r"\btpg_z\b", raw_body):
        tpg_axes.add(2)
        uses_tpg = True

    # Add synthetic scalar args for tpg dimensions.
    # These are injected by MLXLauncher at dispatch time.
    if uses_tpg:
        for axis in sorted(tpg_axes):
            tpg_scalar_name = f"__tpg_dim{axis}"
            scalar_names.append(tpg_scalar_name)
            scalar_types.append("uint")

    # Build header (device functions only — MLX provides metal_stdlib)
    header_parts = []
    for line in pre_kernel.split("\n"):
        line_s = line.strip()
        if line_s.startswith("#include") and "metal_stdlib" not in line_s:
            header_parts.append(line_s)

    device_funcs = _extract_device_functions(pre_kernel)
    if device_funcs:
        header_parts.append("")
        header_parts.append(device_funcs)

    header = "\n".join(header_parts)

    # Build body preamble: local variable declarations that reference
    # thread_position_in_grid / threads_per_threadgroup.
    # MLX auto-injects these as kernel parameters when they appear in source.
    preamble_lines = []

    if uses_2d:
        # 2D: compute pid/lid per axis from injected thread variables
        preamble_lines.append("    // MLX thread variable mapping")
        preamble_lines.append("    uint __pid_x = thread_position_in_grid.x / threads_per_threadgroup.x;")
        preamble_lines.append("    uint __pid_y = thread_position_in_grid.y / threads_per_threadgroup.y;")
        preamble_lines.append("    uint __pid_z = thread_position_in_grid.z / threads_per_threadgroup.z;")
        preamble_lines.append("    uint __lid_x = thread_position_in_grid.x % threads_per_threadgroup.x;")
        preamble_lines.append("    uint __lid_y = thread_position_in_grid.y % threads_per_threadgroup.y;")
        preamble_lines.append("    uint __lid_z = thread_position_in_grid.z % threads_per_threadgroup.z;")
        preamble_lines.append("    uint __tid_x = thread_position_in_grid.x;")

        # Replace the body's decomposition lines with our computed values
        raw_body = re.sub(r"uint\s+pid\s*=\s*pid3\.x\s*;", "uint pid = __pid_x;", raw_body)
        raw_body = re.sub(r"uint\s+lid\s*=\s*lid3\.x\s*;", "uint lid = __lid_x;", raw_body)
        raw_body = re.sub(r"uint\s+tid\s*=\s*tid3\.x\s*;", "uint tid = __tid_x;", raw_body)
        raw_body = re.sub(r"uint\s+pid_y\s*=\s*pid3\.y\s*;", "uint pid_y = __pid_y;", raw_body)
        raw_body = re.sub(r"uint\s+pid_z\s*=\s*pid3\.z\s*;", "uint pid_z = __pid_z;", raw_body)
    else:
        # 1D: pid/lid/tid were kernel params in original MSL — declare as locals
        preamble_lines.append("    // MLX thread variable mapping")
        preamble_lines.append("    uint pid = thread_position_in_grid.x / threads_per_threadgroup.x;")
        preamble_lines.append("    uint lid = thread_position_in_grid.x % threads_per_threadgroup.x;")
        preamble_lines.append("    uint tid = thread_position_in_grid.x;")

    if uses_simd:
        # MLX injects simdgroup_index_in_threadgroup when referenced in source
        preamble_lines.append("    uint sgitg = simdgroup_index_in_threadgroup;")
        preamble_lines.append("    uint tiisg = thread_index_in_simdgroup;")

    if uses_tpg:
        # tpg (threadgroups_per_grid) isn't auto-injected by MLX.
        # Metal's [[threadgroups_per_grid]] attribute is not available through
        # MLX's metal_kernel API, so we pass the grid dimensions as scalar
        # arguments injected by the launcher at dispatch time.
        if 0 in tpg_axes:
            preamble_lines.append("    uint tpg = __tpg_dim0;")
        if 1 in tpg_axes:
            preamble_lines.append("    uint tpg_y = __tpg_dim1;")
        if 2 in tpg_axes:
            preamble_lines.append("    uint tpg_z = __tpg_dim2;")

        # Strip the original tpg decomposition lines from the body
        # (emitted by msl_emitter for the 2D case: uint tpg = tpg3.x; etc.)
        raw_body = re.sub(r"\s*uint\s+tpg\s*=\s*tpg3\.x\s*;\n?", "\n", raw_body)
        raw_body = re.sub(r"\s*uint\s+tpg_y\s*=\s*tpg3\.y\s*;\n?", "\n", raw_body)
        raw_body = re.sub(r"\s*uint\s+tpg_z\s*=\s*tpg3\.z\s*;\n?", "\n", raw_body)

    # The original signature is discarded. Any surviving reference to one of
    # its thread parameters must be supplied by OUR preamble, not by a caller's
    # output-index hint. In particular pid_m=pid3.x and lid=_lid3.x are not the
    # canonical decomposition spellings rewritten above (GitHub issue #2).
    # Check the transformed body, and ignore quoted text before comments so a
    # comment delimiter inside a string cannot alter the scan.
    preamble = "\n".join(preamble_lines)
    supplied = set(re.findall(r"\buint(?:3)?\s+(\w+)\s*=", preamble))
    code = re.sub(r'"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'|//[^\n]*|/\*[\s\S]*?\*/', "", raw_body)
    unresolved = sorted(name for name in thread_vars - supplied if re.search(r"\b" + re.escape(name) + r"\b", code))
    if unresolved:
        raise MetalNonRecoverableError(
            "MLX route: extraction would discard live thread parameters "
            + ", ".join(unresolved)
            + "; their signature mapping is unsupported. Refusing before lazy shader construction."
        )

    body = preamble + "\n" + raw_body

    return MSLExtraction(
        kernel_name=kernel_name,
        body=body,
        header=header,
        input_names=input_names,
        output_names=output_names,
        scalar_names=scalar_names,
        scalar_types=scalar_types,
        output_ptr_indices=output_ptr_idx_set,
        uses_simd=uses_simd,
        uses_2d=uses_2d,
        uses_tpg=uses_tpg,
        tpg_axes=tpg_axes if tpg_axes else None,
        arg_positions=arg_positions,
    )


def _parse_signature(sig_text: str):
    """Parse kernel signature to extract buffer args and thread variables.

    Returns:
        (ptr_args, scalar_args, thread_vars)
    """
    ptr_args = []
    scalar_args = []
    thread_vars = set()
    ptr_positions, scalar_positions = [], []

    for m in re.finditer(
        r"(?:volatile\s+)?device\s+(?:const\s+)?(\w+)\*\s+(\w+)\s+\[\[buffer\((\d+)\)\]\]",
        sig_text,
    ):
        dtype, name = m.group(1), m.group(2)
        ptr_args.append((name, dtype))
        ptr_positions.append(int(m.group(3)))

    for m in re.finditer(
        r"constant\s+(\w+)&\s+(\w+)\s+\[\[buffer\((\d+)\)\]\]",
        sig_text,
    ):
        dtype, name = m.group(1), m.group(2)
        scalar_args.append((name, dtype))
        scalar_positions.append(int(m.group(3)))

    for m in re.finditer(r"uint3?\s+(\w+)\s+\[\[", sig_text):
        thread_vars.add(m.group(1))

    return ptr_args, scalar_args, thread_vars, ptr_positions + scalar_positions


def _extract_device_functions(pre_kernel: str) -> str:
    """Extract device functions from code before the kernel."""
    lines = pre_kernel.split("\n")
    func_lines = []
    in_func = False

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("#include") or stripped.startswith("using "):
            continue
        if not stripped:
            if in_func:
                func_lines.append(line)
            continue
        if ("void " in stripped or "float " in stripped or "int " in stripped) and not stripped.startswith("kernel "):
            in_func = True
        if in_func:
            func_lines.append(line)

    return "\n".join(func_lines).strip()
